# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [
  { name: 'srvapache', ip: '192.168.56.51' },
  { name: 'srvcaddy',  ip: '192.168.56.52' }
]

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"

  hosts.each do |host|
    config.vm.define host[:name] do |node|
      node.vm.hostname = host[:name]
      node.vm.network :private_network, ip: host[:ip]

      config.vm.provision 'shell', path: 'provision/' +  host[:name] + '.sh'
    end
  end
end
